### ISSUE TITLE
Keypress registers events from "sleeping" console

### ISSUE THREAD

**Issue by adrfantini** [gaborcsardi/keypress#2]
If I do

```
Sys.sleep(5); a <- keypress()
```

Then, before the sleep stops, I press arrow buttons, keypress() will register some of those buttons as keypresses and save them in `a`. This is unwanted and does not happen with readline().

In my usecase, I wrote a program that reacts to arrows by moving a point on a plot. keypress() is called inside a while loop, and the plot updated accordingly. It takes a fraction of a second each time to replot the image, so if I hold an arrow button down, many keypress() calls end up being full of things like `"\033[C\033[C\033[C\033"`.

This of course gets worse on slower computers or with heavier code.

**Comment by gaborcsardi** [comment]
Hmmm, for me `readline()` does the same on my OSX terminal. E.g.

``` r
Sys.sleep(5); a <- readline()
```

Will happily read `a` while sleeping.

**Comment by adrfantini** [comment]
xTerm here on Linux.
readline() doesn't read "left", "down" and "right" on my system.
e.g.

```
> Sys.sleep(5); a <- readline()
^[[B^[[B^[[C^[[C^[[B^[[B^[[D^[[D^[[D^[[D56
> a
[1] "56"
```

But bad news for "up", because it recalls previous history items, which appear in the readline() input line and, if [Enter] is pressed, are recognized as the typed content `a`.

**Comment by gaborcsardi** [comment]
OK, I think I know how to fix this. `keypress()` should only take a single keypress from the input, and leave the rest there for future `keypress()` (or other) calls. Right? Is this what you want?

**Comment by adrfantini** [comment]
Not exactly. Keypress should ignore all key events that occur _before_ the keypress call. 

e.g.
1) I plot an image which takes some time to render
2) I press "up"  twice
3) Plot finishes rendering and the next line, `keypress()`, is called
4) I press "up" again.

On my system, right now keypress registers the equivalent of "up up up", instead of just "up".

**Comment by gaborcsardi** [comment]
I don't think this is a good idea in general. People type quickly and "forward", even when the machine is doing something else. The keyboard and the OS have buffers and keep all these key press events.

> 1) I plot an image which takes some time to render
> 2) I press "up" twice
> 3) Plot finishes rendering and the next line, keypress(), is called
> 4) I press "up" again.

I think if you press `up` three times, you want to get three `up` events in your program. Losing key presses is very annoying. Right now you get one `upupup` event, which is clearly wrong. You should get three events, for three calls to `keypress()`.

If you really want to drop events, then I can add a non-blocking `keypress()` call. Then you can keep calling this until there is no input, and then do a blocking call. That would be like dropping the two `up` events that happened "in between". (Of course if somebody presses `up` **right before** your first `keypress()` call, that will be lost, too, this is the annoying part.)

**Comment by adrfantini** [comment]
You have a point. For some usages the current situation is wanted, for some others it is not.
A lock option would be most welcome indeed.

**Comment by adrfantini** [comment]
Thanks, small niggle:
with block=TRUE, I can't seem to make keypress() register a single Escape command (\033). It only registers [Esc] twice (\033\033).

**Comment by gaborcsardi** [comment]
Should be good now. It is hard to make things right without something full-fledged like libuv.

**Comment by adrfantini** [comment]
Excellent, thanks!
